export const RoutesManagement = {
  AUTH: { path: 'auth' },
  LOGIN: { path: 'login' },
  MAIN: { path: 'main' },
  DASHBOARD: { path: 'dashboard' },
  CLINICS: { path: 'clinics' },
  DOCTORS: { path: 'doctors' },
  DOCTOR_CLINICS: { path: 'doctors/:doctorId/clinics' },
  EMPLOYEES: { path: 'employees' },
  TREASURY: { path: 'treasury' },
  SPECIAL_OFFERS: { path: 'special-offers' },
  SPECIAL_OFFER_DETAILS: { path: 'special-offers/:id' },
  DOCTOR_WALLET: { path: 'doctor-wallet' },
  DOCTOR_WALLET_TRANSACTION_DETAILS: { path: 'doctor-wallet/transactions/:id' },
  DOCTOR_SCHEDULES: { path: 'doctor-schedules' },
  TODAY_DOCTOR_SCHEDULES: { path: 'today-doctor-schedules' },
  USER_LOGIN_LOGS: { path: 'user-login-logs' },
  PROFILE: { path: 'profile' },
  CHANGE_PASSWORD: { path: 'change-password' },
  ADMIN_PASSWORD_MANAGEMENT: { path: 'admin-password-management' },
  APPOINTMENTS: { path: 'appointments' },
  APPOINTMENT_BOOKING: { path: 'appointment-booking' },
  SCHEDULE_APPOINTMENTS: { path: 'schedule-appointments/:scheduleId' },
  APPOINTMENT_DETAILS: { path: 'appointment-details/:id' },
  DOCTOR_TODAY_APPOINTMENTS: { path: 'doctor-today-appointments' },
  COMPANIES: { path: 'companies' },
  COMPANY_ORDERS: { path: 'companies/:id/orders' },
  OFFER_ORDER_DETAILS: { path: 'offer-orders/:id' },
} as const;

export const HospitalName = 'جميلة' as const;
